### ISSUE TITLE
Enhance `Evaluate()`.

### ISSUE THREAD

**Issue by Mostafa-ElBasiouny** [Mostafa-ElBasiouny/S2-G6-GreenEye#17]
Allow `Evaluate()` to automatically adjust its evaluation based on the user-specified safe readings.
---
**For example:**
If the sensor readings range from 0 - 100, and the safe ranges set by the user are 40 - 60; the method should create an event based on the following criteria:
- Lower than `40` - Create a critical event indicating **low** readings: `reading < 40`.
- Higher than `60` - Create a critical event indicating **high** readings: `reading > 60`.
- Lower `15%` of the range - Create a warning event indicating that readings are reaching **low** values: `reading >= 40 && reading <= 43`.
- Upper `15%` of the range - Create a warning event indicating that readings are reaching **high** values: `reading <= 60 && reading >= 57`.

###### *15% of (60-40) is 3*
---
https://github.com/Mostafa-ElBasiouny/S2-G6-GreenEye/blob/be85d56d3a34d75219fadd741354f9766ec1b1de/S2-G6-GreenEye/source/sensors/air_humidity.cpp#L71
https://github.com/Mostafa-ElBasiouny/S2-G6-GreenEye/blob/be85d56d3a34d75219fadd741354f9766ec1b1de/S2-G6-GreenEye/source/sensors/air_humidity.cpp#L83

**Comment by armaksymov** [comment]
So, for our alerts, we decided to go with two types: critical and warnings.
Critical Alert will be 10% of the measurement scale (for instance user has lower limit of 40 and upper of 60, on 0 - 100 scale), so the critical alert will be triggered on lower limit - 10% of the scale, so 40 - (100 * 0.1), and on higher limit - +10% of the scale, so 60 + (100 * 0.1).
And for the warning it will be 5% of the scale.

**Comment by Mostafa-ElBasiouny** [comment]
@Hashad-ar has resolved the issue.
